# infra/docker-compose.yml
services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092" # Kafka for host apps
      - "9644:9644" # Redpanda Admin API
    command: >
      redpanda start
      --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0
      --kafka-addr INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      --advertise-kafka-addr INTERNAL://redpanda:29092,EXTERNAL://127.0.0.1:9092
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      # Console runs inside the compose network → use the INTERNAL listener
      KAFKA_BROKERS: redpanda:29092
      # Enable admin features (topics, consumer groups, configs, etc.)
      REDPANDA_ADMIN_URLS: http://redpanda:9644
    ports:
      - "8080:8080"
    depends_on:
      redpanda:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: opensettle-postgres
    environment:
      POSTGRES_USER: opensettle
      POSTGRES_PASSWORD: opensettle
      POSTGRES_DB: opensettle
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opensettle -d opensettle"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: opensettle-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true" # enable OTLP gRPC/HTTP
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "14250:14250" # gRPC collector
      - "14268:14268" # HTTP collector
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:16686 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redpanda-data:
  pg-data:
  redis-data:
